// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package da_generated

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getActiveWebhooksStmt, err = db.PrepareContext(ctx, getActiveWebhooks); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveWebhooks: %w", err)
	}
	if q.getActiveWebhooksPaginatedStmt, err = db.PrepareContext(ctx, getActiveWebhooksPaginated); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveWebhooksPaginated: %w", err)
	}
	if q.getWebhookByIdStmt, err = db.PrepareContext(ctx, getWebhookById); err != nil {
		return nil, fmt.Errorf("error preparing query GetWebhookById: %w", err)
	}
	if q.getWebhooksByIDsStmt, err = db.PrepareContext(ctx, getWebhooksByIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetWebhooksByIDs: %w", err)
	}
	if q.insertWebhookLogStmt, err = db.PrepareContext(ctx, insertWebhookLog); err != nil {
		return nil, fmt.Errorf("error preparing query InsertWebhookLog: %w", err)
	}
	if q.scanDLQForRedriveStmt, err = db.PrepareContext(ctx, scanDLQForRedrive); err != nil {
		return nil, fmt.Errorf("error preparing query ScanDLQForRedrive: %w", err)
	}
	if q.scanFailedPartnersStmt, err = db.PrepareContext(ctx, scanFailedPartners); err != nil {
		return nil, fmt.Errorf("error preparing query ScanFailedPartners: %w", err)
	}
	if q.updateWebhookStmt, err = db.PrepareContext(ctx, updateWebhook); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWebhook: %w", err)
	}
	if q.updateWebhookLogRedriveStatusStmt, err = db.PrepareContext(ctx, updateWebhookLogRedriveStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWebhookLogRedriveStatus: %w", err)
	}
	if q.updateWebhookLogStatusStmt, err = db.PrepareContext(ctx, updateWebhookLogStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWebhookLogStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getActiveWebhooksStmt != nil {
		if cerr := q.getActiveWebhooksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveWebhooksStmt: %w", cerr)
		}
	}
	if q.getActiveWebhooksPaginatedStmt != nil {
		if cerr := q.getActiveWebhooksPaginatedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveWebhooksPaginatedStmt: %w", cerr)
		}
	}
	if q.getWebhookByIdStmt != nil {
		if cerr := q.getWebhookByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWebhookByIdStmt: %w", cerr)
		}
	}
	if q.getWebhooksByIDsStmt != nil {
		if cerr := q.getWebhooksByIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWebhooksByIDsStmt: %w", cerr)
		}
	}
	if q.insertWebhookLogStmt != nil {
		if cerr := q.insertWebhookLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertWebhookLogStmt: %w", cerr)
		}
	}
	if q.scanDLQForRedriveStmt != nil {
		if cerr := q.scanDLQForRedriveStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing scanDLQForRedriveStmt: %w", cerr)
		}
	}
	if q.scanFailedPartnersStmt != nil {
		if cerr := q.scanFailedPartnersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing scanFailedPartnersStmt: %w", cerr)
		}
	}
	if q.updateWebhookStmt != nil {
		if cerr := q.updateWebhookStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWebhookStmt: %w", cerr)
		}
	}
	if q.updateWebhookLogRedriveStatusStmt != nil {
		if cerr := q.updateWebhookLogRedriveStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWebhookLogRedriveStatusStmt: %w", cerr)
		}
	}
	if q.updateWebhookLogStatusStmt != nil {
		if cerr := q.updateWebhookLogStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWebhookLogStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                DBTX
	tx                                *sql.Tx
	getActiveWebhooksStmt             *sql.Stmt
	getActiveWebhooksPaginatedStmt    *sql.Stmt
	getWebhookByIdStmt                *sql.Stmt
	getWebhooksByIDsStmt              *sql.Stmt
	insertWebhookLogStmt              *sql.Stmt
	scanDLQForRedriveStmt             *sql.Stmt
	scanFailedPartnersStmt            *sql.Stmt
	updateWebhookStmt                 *sql.Stmt
	updateWebhookLogRedriveStatusStmt *sql.Stmt
	updateWebhookLogStatusStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                tx,
		tx:                                tx,
		getActiveWebhooksStmt:             q.getActiveWebhooksStmt,
		getActiveWebhooksPaginatedStmt:    q.getActiveWebhooksPaginatedStmt,
		getWebhookByIdStmt:                q.getWebhookByIdStmt,
		getWebhooksByIDsStmt:              q.getWebhooksByIDsStmt,
		insertWebhookLogStmt:              q.insertWebhookLogStmt,
		scanDLQForRedriveStmt:             q.scanDLQForRedriveStmt,
		scanFailedPartnersStmt:            q.scanFailedPartnersStmt,
		updateWebhookStmt:                 q.updateWebhookStmt,
		updateWebhookLogRedriveStatusStmt: q.updateWebhookLogRedriveStatusStmt,
		updateWebhookLogStatusStmt:        q.updateWebhookLogStatusStmt,
	}
}
