// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package da_generated

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Webhook struct {
	ID        string          `json:"id"`
	PartnerID string          `json:"partner_id"`
	Status    string          `json:"status"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type WebhookLogs struct {
	ID        int64  `json:"id"`
	WebhookID string `json:"webhook_id"`
	PartnerID string `json:"partner_id"`
	// the event data sent to partner
	EventPayload json.RawMessage `json:"event_payload"`
	// HTTP status code from partner
	ResponseStatus sql.NullInt32 `json:"response_status"`
	// response body from partner
	ResponseBody sql.NullString `json:"response_body"`
	// error message if failed
	ErrorMessage  sql.NullString `json:"error_message"`
	SentAt        time.Time      `json:"sent_at"`
	RedriveCount  int32          `json:"redrive_count"`
	IsResolved    bool           `json:"is_resolved"`
	NextRedriveAt sql.NullTime   `json:"next_redrive_at"`
	// status: PENDING, SUCCESS, FAILED, EXHAUSTED
	Status sql.NullString `json:"status"`
}
