// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package da_generated

import (
	"context"
)

type Querier interface {
	GetWebhookById(ctx context.Context, id string) (*Webhook, error)
	GetWebhooksByIDs(ctx context.Context, webhookIds []string) ([]*Webhook, error)
	InsertWebhookLog(ctx context.Context, arg *InsertWebhookLogParams) error
	ScanDLQForRedrive(ctx context.Context, limit int32) ([]*ScanDLQForRedriveRow, error)
	ScanFailedPartners(ctx context.Context) ([]string, error)
	UpdateWebhook(ctx context.Context, arg *UpdateWebhookParams) (int64, error)
	UpdateWebhookLogRedriveStatus(ctx context.Context, arg *UpdateWebhookLogRedriveStatusParams) error
	UpdateWebhookLogStatus(ctx context.Context, arg *UpdateWebhookLogStatusParams) error
}

var _ Querier = (*Queries)(nil)
