// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: table_webhook.sql

package da_generated

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
)

const getActiveWebhooks = `-- name: GetActiveWebhooks :many
SELECT id, partner_id, status, metadata, created_at, updated_at FROM webhook WHERE status = 'active'
`

func (q *Queries) GetActiveWebhooks(ctx context.Context) ([]*Webhook, error) {
	rows, err := q.query(ctx, q.getActiveWebhooksStmt, getActiveWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveWebhooksPaginated = `-- name: GetActiveWebhooksPaginated :many
SELECT id, partner_id, status, metadata, created_at, updated_at FROM webhook WHERE status = 'active' ORDER BY id LIMIT ? OFFSET ?
`

type GetActiveWebhooksPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetActiveWebhooksPaginated(ctx context.Context, arg *GetActiveWebhooksPaginatedParams) ([]*Webhook, error) {
	rows, err := q.query(ctx, q.getActiveWebhooksPaginatedStmt, getActiveWebhooksPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhookById = `-- name: GetWebhookById :one
select id, partner_id, status, metadata, created_at, updated_at
from webhook where id = ?
`

func (q *Queries) GetWebhookById(ctx context.Context, id string) (*Webhook, error) {
	row := q.queryRow(ctx, q.getWebhookByIdStmt, getWebhookById, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWebhooksByIDs = `-- name: GetWebhooksByIDs :many
SELECT id, partner_id, status, metadata, created_at, updated_at FROM webhook WHERE id IN (/*SLICE:webhook_ids*/?)
`

func (q *Queries) GetWebhooksByIDs(ctx context.Context, webhookIds []string) ([]*Webhook, error) {
	query := getWebhooksByIDs
	var queryParams []interface{}
	if len(webhookIds) > 0 {
		for _, v := range webhookIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:webhook_ids*/?", strings.Repeat(",?", len(webhookIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:webhook_ids*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWebhookLog = `-- name: InsertWebhookLog :exec
INSERT INTO webhook_logs (webhook_id, partner_id, event_payload, response_status, response_body, error_message, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertWebhookLogParams struct {
	WebhookID      string          `json:"webhook_id"`
	PartnerID      string          `json:"partner_id"`
	EventPayload   json.RawMessage `json:"event_payload"`
	ResponseStatus sql.NullInt32   `json:"response_status"`
	ResponseBody   sql.NullString  `json:"response_body"`
	ErrorMessage   sql.NullString  `json:"error_message"`
	Status         sql.NullString  `json:"status"`
}

func (q *Queries) InsertWebhookLog(ctx context.Context, arg *InsertWebhookLogParams) error {
	_, err := q.exec(ctx, q.insertWebhookLogStmt, insertWebhookLog,
		arg.WebhookID,
		arg.PartnerID,
		arg.EventPayload,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ErrorMessage,
		arg.Status,
	)
	return err
}

const updateWebhook = `-- name: UpdateWebhook :execrows
insert into webhook (id, status, partner_id, metadata)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    status = ?,
    metadata = ?
`

type UpdateWebhookParams struct {
	ID        string          `json:"id"`
	Status    string          `json:"status"`
	PartnerID string          `json:"partner_id"`
	Metadata  json.RawMessage `json:"metadata"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg *UpdateWebhookParams) (int64, error) {
	result, err := q.exec(ctx, q.updateWebhookStmt, updateWebhook,
		arg.ID,
		arg.Status,
		arg.PartnerID,
		arg.Metadata,
		arg.Status,
		arg.Metadata,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
