// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: table_webhook_log.sql

package da_generated

import (
	"context"
	"database/sql"
	"encoding/json"
)

const scanDLQForRedrive = `-- name: ScanDLQForRedrive :many
SELECT id, webhook_id, partner_id, event_payload, redrive_count
FROM webhook_logs
WHERE is_resolved = FALSE
  AND redrive_count < 5
  AND (next_redrive_at IS NULL OR next_redrive_at <= NOW())
LIMIT ?
`

type ScanDLQForRedriveRow struct {
	ID           int64           `json:"id"`
	WebhookID    string          `json:"webhook_id"`
	PartnerID    string          `json:"partner_id"`
	EventPayload json.RawMessage `json:"event_payload"`
	RedriveCount int32           `json:"redrive_count"`
}

func (q *Queries) ScanDLQForRedrive(ctx context.Context, limit int32) ([]*ScanDLQForRedriveRow, error) {
	rows, err := q.query(ctx, q.scanDLQForRedriveStmt, scanDLQForRedrive, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ScanDLQForRedriveRow
	for rows.Next() {
		var i ScanDLQForRedriveRow
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.PartnerID,
			&i.EventPayload,
			&i.RedriveCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanFailedPartners = `-- name: ScanFailedPartners :many
SELECT DISTINCT partner_id
FROM webhook_logs
WHERE is_resolved = FALSE
  AND redrive_count < 5
`

func (q *Queries) ScanFailedPartners(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.scanFailedPartnersStmt, scanFailedPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var partner_id string
		if err := rows.Scan(&partner_id); err != nil {
			return nil, err
		}
		items = append(items, partner_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookLogRedriveStatus = `-- name: UpdateWebhookLogRedriveStatus :exec
UPDATE webhook_logs
SET redrive_count = redrive_count + 1,
    is_resolved = ?,
    error_message = ?,
    next_redrive_at = ?
WHERE id = ?
`

type UpdateWebhookLogRedriveStatusParams struct {
	IsResolved    bool           `json:"is_resolved"`
	ErrorMessage  sql.NullString `json:"error_message"`
	NextRedriveAt sql.NullTime   `json:"next_redrive_at"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateWebhookLogRedriveStatus(ctx context.Context, arg *UpdateWebhookLogRedriveStatusParams) error {
	_, err := q.exec(ctx, q.updateWebhookLogRedriveStatusStmt, updateWebhookLogRedriveStatus,
		arg.IsResolved,
		arg.ErrorMessage,
		arg.NextRedriveAt,
		arg.ID,
	)
	return err
}

const updateWebhookLogStatus = `-- name: UpdateWebhookLogStatus :exec
UPDATE webhook_logs
SET status = ?
WHERE id = ?
`

type UpdateWebhookLogStatusParams struct {
	Status sql.NullString `json:"status"`
	ID     int64          `json:"id"`
}

func (q *Queries) UpdateWebhookLogStatus(ctx context.Context, arg *UpdateWebhookLogStatusParams) error {
	_, err := q.exec(ctx, q.updateWebhookLogStatusStmt, updateWebhookLogStatus, arg.Status, arg.ID)
	return err
}
